FROM node:18.16.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force

ENV NODE_OPTIONS=--max_old_space_size=4096

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]